# Generated by Django 2.1 on 2018-08-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMailPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Текст письма')),
                ('created', models.DateTimeField()),
                ('sender', models.CharField(max_length=1000, verbose_name='Отправитель')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('moderated', models.BooleanField(default=True)),
            ],
        ),
    ]
